In [1]:
# While statement

In [2]:
x = int(input("Enter a whole number no greater than eleven:"))
while x>11:
    print("This is greater than eleven.Please try again")
    x = int(input("Enter a whole number no greater than eleven:"))
print("Your number is",x)

Enter a whole number no greater than eleven:12
This is greater than eleven.Please try again
Enter a whole number no greater than eleven:14
This is greater than eleven.Please try again
Enter a whole number no greater than eleven:15
This is greater than eleven.Please try again
Enter a whole number no greater than eleven:10
Your number is 10


In [1]:
# if statement
# see the difference when you input the number greater than 11. You have only two steps here. But in while, it continues.
x = int(input("Enter a whole number no greater than eleven:"))
if x>11:
    print("This is greater than eleven.Please try again")
    x = int(input("Enter a whole number no greater than eleven:"))
print("Your number is",x)

Enter a whole number no greater than eleven:12
This is greater than eleven.Please try again
Enter a whole number no greater than eleven:14
Your number is 14


# Some examples

In [4]:
n = int(input("Enter an integer:"))
if n%2 ==0:
    print("even")
else:
    print("odd")

Enter an integer:4
even


In [5]:
from math import sqrt
r = [1.0, 1.5, -2]
length = sqrt(r[0]**2 + r[1]**2 + r[2]**2)
print(length)

2.692582403567252


In [6]:
r = [1.0,1.5,-2.2]
x = 0.8
r.append(2*x+2)
print(r)

[1.0, 1.5, -2.2, 3.6]


In [7]:
r = []
r.append(1.0)
r.append(2)
r.append(2.6)
print(r)

[1.0, 2, 2.6]


In [2]:
from numpy import array 
a = array([[1,2,3],[4,5,6]],int)
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
from numpy import zeros
a = zeros([2,2],int)
# print(a)
a[0,1] = 1
a[1,1] = -1
print(a)

[[ 0  1]
 [ 0 -1]]


In [7]:
from numpy import loadtxt
a = loadtxt("array.txt",float)
print(a)

[1.  1.4 2.9]


In [4]:
import pandas as pd
import numpy as np
a = pd.read_csv("noise_survey.csv") # https://github.com/dharmapaudel/data 
a.head()

A   B   C   D   E   F   G   H   I   J  ...   N   O   P   Q   R   S   T  \
0  79  80  82  83  84  85  82  82  82  69  ...  73  74  75  76  77  78  79   
1  80  81  83  83  83  83  83  83  83  83  ...  83  83  83  83  83  83  83   
2  81  82  81  84  81  81  81  81  81  81  ...  81  81  81  81  81  81  81   
3  79  80  82  85  82  83  84  85  86  82  ...  73  74  75  76  77  78  79   
4  80  81  78  78  78  78  78  78  78  83  ...  78  78  78  78  78  78  78   

    U   V   W  
0  80  81  82  
1  83  83  83  
2  81  81  81  
3  80  81  82  
4  78  78  78  

[5 rows x 23 columns]

In [17]:
from numpy import array
a = array([1,2,3,4],int)
b = 2*a
print(b)
#compare it with list operation:
a = [1,2,3,4]
b = 2*a
print(b)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


In [16]:
a = [1,2,3,4]
b = 2*a
print(b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [12]:
c = [1,2,3,4]
d = 2*c[0]
c.append(d)
print(c)

[1, 2, 3, 4, 2]


In [19]:
a = array([1,2,3,4],int)
b = array([2,4,6,8],int)
print(a+b)

[ 3  6  9 12]


In [21]:
a = array([[2,4,6],[1,5,8]],int)
print(a.size)
print(a.shape)

6
(2, 3)


In [23]:
r = range(4)
for n in r:
    print("hello")

hello
hello
hello
hello


In [24]:
r = range(6)
for n in r:
    print(n**2)

0
1
4
9
16
25


In [27]:
# Program Sum
s = 0.0
for k in range (1,201):
    s += 1/k
print(s)

5.878030948121446


# User defined function 

In [2]:
from math import cos, sin , sqrt
def distance(r,theta,z):
    x = r*cos(theta)
    y = r*sin(theta)
    d = sqrt(x**2+y**2+z**2)
    return d
D= distance(1.0,0.1,-2)
print(D)

2.23606797749979


In [3]:
D= distance(1.0,0.1,-2)
print(D)

2.23606797749979


In [7]:
def cartesian(r, theta):
    x = r*cos(theta)
    y = r*sin(theta)
    position = [x,y]
    return position
d = cartesian(1,40)
print(d)

[-0.6669380616522619, 0.7451131604793488]
